version: '3'

services:
  balanceNotifier:
    image: "saittisk/balance_notifier:v0.0.1"
    volumes:
      - type: volume
        source: mydata
        target: /db/data
      - type: bind
        source: /creds/google_creds.json
        target: /creds/google_creds.json
    environment:
      - API_KEY=${API_KEY}
      - API_SECRET=${API_SECRET}
      - BOT_TOKEN=${BOT_TOKEN}
      - CHAT_ID=${CHAT_ID}
      - RECORD_DATA_IN_GOOGLE_SHEETS=${RECORD_DATA_IN_GOOGLE_SHEETS}
      - STABLECOINS_BALANCE_SPREADSHEET_ID=${STABLECOINS_BALANCE_SPREADSHEET_ID}
      - STABLECOINS_SPREADSHEET=${STABLECOINS_SPREADSHEET}
      - SERVICE_ACCOUNT_FILE_PATH=${SERVICE_ACCOUNT_FILE_PATH}

volumes:
  mydata:
